/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms.mavenproject1;
import javax.swing.*;
/**
 *
 * @author frank
 */
public class tester extends javax.swing.JFrame {
public String measurement;
    /**
     * Creates new form tester
     */
    public tester() {
        initComponents();
    }

    private double convertMeasurement(double value, String unit1, String unit2) {
    // Conversion logic based on the selected units
    // Implement your conversion algorithm here
    // You can use if-else statements or switch case to handle different conversions
    double result = 0.0;
    // Example conversion from meters to kilometers
    if (unit1.equals(unit2)){return value;}
    
    if (unit1.equals("(M) Meters") && unit2.equals("(KM)  Kilometers")) {
        return value / 1000.0;
    }
    else if (unit1.equals("(KM)  Kilometers") && unit2.equals("(M) Meters")) {
        return value * 1000.0;
    } else if (unit1.equals("(M) Meters") && unit2.equals("(CM)  Centimeters")) {
       return value * 100.0;
    } else if (unit1.equals("(CM)  Centimeters") && unit2.equals("(M) Meters")) {
        return value / 100.0;
    } else if (unit1.equals("(M) Meters") && unit2.equals("(MM)  Millimeters")) {
        return value * 1000.0;
    } else if (unit1.equals("(MM)  Millimeters") && unit2.equals("(M) Meters")) {
        return value / 1000.0;
    } else if (unit1.equals("(KM)  Kilometers") && unit2.equals("(CM)  Centimeters")) {
        return value * 100000.0;
    } else if (unit1.equals("(CM)  Centimeters") && unit2.equals("(KM)  Kilometers")) {
        return value / 100000.0;
    } else if (unit1.equals("(KM)  Kilometers") && unit2.equals("(MM)  Millimeters")) {
        return value * 1000000.0;
    } else if (unit1.equals("(MM)  Millimeters") && unit2.equals("(KM)  Kilometers")) {
        return value / 1000000.0;
    } else if (unit1.equals("(CM)  Centimeters") && unit2.equals("(MM)  Millimeters")) {
        return value * 10.0;
    } else if (unit1.equals("(MM)  Millimeters") && unit2.equals("(CM)  Centimeters")) {
        return value / 10.0;
    } else if (unit1.equals("(MI)  Miles") && unit2.equals("(YD)  Yards")) {
        return value * 1760.0;
    } else if (unit1.equals("(YD)  Yards") && unit2.equals("(MI)  Miles")) {
        return value / 1760.0;
    } else if (unit1.equals("(MI)  Miles") && unit2.equals("(FT)  Feet")) {
        return value * 5280.0;
    } else if (unit1.equals("(FT)  Feet") && unit2.equals("(MI)  Miles")) {
        return value / 5280.0;
    } else if (unit1.equals("(MI)  Miles") && unit2.equals("(IN)  Inches")) {
        return value * 63360.0;
    } else if (unit1.equals("(IN)  Inches") && unit2.equals("(MI)  Miles")) {
        return value / 63360.0;
    } else if (unit1.equals("(MI)  Miles") && unit2.equals("(NM)  Nautical Miles")) {
        return value * 0.868976;
    } else if (unit1.equals("(NM)  Nautical Miles") && unit2.equals("(MI)  Miles")) {
        return value / 0.868976;}
    
    if (unit1.equals("(C) Celsius") && unit2.equals("(F) Fahrenheit")) {
        return (value * 9.0 / 5.0) + 32.0;
    } else if (unit1.equals("(F) Fahrenheit") && unit2.equals("(C) Celsius")) {
        return (value - 32.0) * 5.0 / 9.0;
    }
    
    if (unit1.equals("(Kg) Kilograms") && unit2.equals("(lbs) Pounds")) {
        return value * 2.20462;
    } else if (unit1.equals("(lbs) Pounds") && unit2.equals("(Kg) Kilograms")) {
        return value / 2.20462;
    }
    
    
return result;
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String[] items = {"Distance", "Temperature", "Weight"};
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Gayathri", 1, 20)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(items));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        jComboBox2.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox2.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "(M) Meters",
            "(KM)  Kilometers",
            "(CM)  Centimeters",
            "(MM)  Millimeters",
            "(MI)  Miles",
            "(YD)  Yards",
            "(FT)  Feet",
            "(IN)  Inches",
            "(NM)  Nautical Miles"}));

jTextField1.setBackground(new java.awt.Color(51, 51, 51));
jTextField1.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
jTextField1.setForeground(new java.awt.Color(255, 255, 255));
jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
jTextField1.setBorder(null);
jTextField1.setText("0.00");
jTextField1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
    }
    });

    jComboBox3.setBackground(new java.awt.Color(51, 51, 51));
    jComboBox3.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
    jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
        "(M) Meters",
        "(KM)  Kilometers",
        "(CM)  Centimeters",
        "(MM)  Millimeters",
        "(MI)  Miles",
        "(YD)  Yards",
        "(FT)  Feet",
        "(IN)  Inches",
        "(NM)  Nautical Miles"}));

jSeparator2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

jButton1.setBackground(new java.awt.Color(51, 51, 51));
jButton1.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
jButton1.setForeground(new java.awt.Color(255, 255, 255));
jButton1.setText("CALCULATE");
jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
    jButton1MouseClicked(evt);
    }
    });

    jButton2.setBackground(new java.awt.Color(51, 51, 51));
    jButton2.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("CLEAR");
    jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButton2MouseClicked(evt);
        }
    });
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(182, 182, 182))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jTextField1.setText("0.00");
        jLabel2.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
        String inputText = jTextField1.getText();
        double inputValue = Double.parseDouble(inputText);

        String selectedUnit1 = (String) jComboBox2.getSelectedItem();
        String selectedUnit2 = (String) jComboBox3.getSelectedItem();
        double convertedValue = convertMeasurement(inputValue, selectedUnit1, selectedUnit2);

        String resultText = String.format("%.2f", convertedValue);
        jLabel2.setText(resultText);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedItem = (String) jComboBox1.getSelectedItem();

        // Update the items in comboBox2 based on the selected item in comboBox1
        if (selectedItem.equals("Distance")) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{
                "(M) Meters",
                "(KM)  Kilometers",
                "(CM)  Centimeters",
                "(MM)  Millimeters",
                "(MI)  Miles",
                "(YD)  Yards",
                "(FT)  Feet",
                "(IN)  Inches",
                "(NM)  Nautical Miles"}));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[]{
                "(M) Meters",
                "(KM)  Kilometers",
                "(CM)  Centimeters",
                "(MM)  Millimeters",
                "(MI)  Miles",
                "(YD)  Yards",
                "(FT)  Feet",           
                "(IN)  Inches",
                "(NM)  Nautical Miles"}));
        } else if (selectedItem.equals("Temperature")) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { 
                "(C) Celsius",
                "(F) Fahrenheit" }));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[] { 
                "(C) Celsius",
                "(F) Fahrenheit" }));
        } else if (selectedItem.equals("Weight")) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { 
                "(lbs) Pounds",
                "(Kg) Kilograms" }));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[] { 
                 "(lbs) Pounds",
                "(Kg) Kilograms" }));
        } 

    }//GEN-LAST:event_jComboBox1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
